# Generated by Django 6.0.6 on 2026-06-12 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=150)),
                ('competition', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('played', 'Played')], default='upcoming', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='matches/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='matches.match')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('scorers', models.JSONField(blank=True, default=list)),
                ('assists', models.JSONField(blank=True, default=list)),
                ('yellow_cards', models.JSONField(blank=True, default=list)),
                ('red_cards', models.JSONField(blank=True, default=list)),
                ('substitutions', models.JSONField(blank=True, default=list)),
                ('possession', models.PositiveIntegerField(default=50)),
                ('shots_on_target', models.PositiveIntegerField(default=0)),
                ('fouls', models.PositiveIntegerField(default=0)),
                ('man_of_the_match', models.CharField(blank=True, max_length=100)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='matches.match')),
            ],
        ),
    ]
